### PR TITLE
Nokia 3.1, 5.1 new firmware likely has fixed the issues.

### PR DESCRIPTION
**Pull request by abdullah-mazed**
This should be tested by more devs, but there is now hope that Nokia is fixing the issues in latest firmware updates.

### CODE REVIEW

**Comment by Perdjesk** [comment]
According to https://www.nokia.com/phones/en_int/security-updates
The firmware listed for Nokia 3.1 in this PR is for May-19 and other SecurityPatches have been released since. 

I am running  00WW_3_180_SP04 | Jul-19, on a Nokia 3.1 and still have to disable DuraSpeed to get WhatsApp notifications.

**Comment by louistsaitszho** [comment]
Update: Nokia just made a blog post, saying that [Evenwell has been disabled for all devices running P](https://community.phones.nokia.com/discussion/51246/tapping-into-android-pies-adaptive-battery-for-optimum-battery-performance) 🎊 🎉 . 

Maybe this PR can be adjusted to reflect not just those 2 phones, but all Nokia devices?

**Comment by Artaud** [comment]
Thanks a lot! I'm merging this in and rewriting it a little to reflect on further development of the situation.

**Comment by Artaud** [comment]
Oh sorry I didn't really see that this PR is about Duraspeed. I believe that Duraspeed hasn't been removed, right?

**Comment by Perdjesk** [comment]
@Artaud  The merged information about the firmware numbers including the changes described in the blog post by Nokia are incorrect.

For Nokia 3.1 the potential firmware upgrade containing improvement is 00WW_3_25B (MR Update and SP (Pie 9) | Aug-19). To be confirmed that it does include the removal of `com.evenwell.powersaving.g3` and the fixes for DuraSpeed.

**Comment by abdullah-mazed** [comment]
In response to: "I am running 00WW_3_180_SP04 | Jul-19, on a Nokia 3.1 and still have to disable DuraSpeed to get WhatsApp notifications."

That's not the latest.
We have tested with 00WW_3_25B in Nokia 3.1.
We could not find anything in syslog from duarspeed, so we believe 3.1 and 5.1 issues are also fixed.

**Comment by ilhamakbari** [comment]
Hello. I don't know if it's the right place to tell you (the contributors), but since I updated my Nokia 5.1 Plus to September SP, I don't have to disable DuraSpeed through ADB to receive notifications. My smartwatch also no longer constantly disconnects every five minutes or so. I don't know about other phones, but I think DuraSpeed is removed for good now on all Nokia's Mediatek phones (or at least only on 5.1 Plus. Can anyone confirm?)

Thank you!

**Pull request merged**
