### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by Artaud**

### CODE REVIEW

**Review by ghostkhumalo09 — APPROVED** [review]

**Comment by pkh709799-byte** [comment]
c6837c17b573474443b791e80bebd6c210752e1a

**Review by Yang062 — APPROVED** [review]

**Comment by pkh709799-byte** [comment]
c6837c1

**Comment by pkh709799-byte** [comment]
GitHub Community Guidelines

**Comment by pkh709799-byte** [comment]
l10n_crowdin_master

**Comment by pkh709799-byte** [comment]
gh pr checkout 340

**Comment by pkh709799-byte** [comment]
gh pr checkout 340

**Comment by pkh709799-byte** [comment]
l10n_crowdin_master

**Comment by pkh709799-byte** [comment]
c6837c1

**Review by Yang062 — APPROVED** [review]

**Pull request closed without merging**
