### PR TITLE
Update example to use Kotlin + Coroutines over deprecated AsyncTask

### PR DESCRIPTION
**Pull request by ed-george**
As Android is now 'Kotlin first', this PR removes the outdated and deprecated use of AsyncTask in the example API documentation and replaces it with a Kotlin equivalent

### CODE REVIEW

**Comment by Artaud** [comment]
Thanks a lot for this! As there might be lots of legacy projects in the wild, I'd keep that Java example around, we could do a tab switcher with both Java and Kotlin code. If you want to do this, please do, otherwise I'll use your Kotlin implementation and put it in tabs switcher.

**Comment by ed-george** [comment]
Not a problem, I am more than happy to contribute to great projects such as this!

Are there existing examples of a tab switcher on the site? I am more than happy to update my PR accordingly. 

I would still advise against promoting the use of AsyncTask for Java though, it is no longer the preferred way in Android to take work off the main thread. Happy to hear your opinion on this.

**Comment by Artaud** [comment]
We've discussed it with @petrnalevka and settled on going with Kotlin only....thanks a lot, I'm merging your PR!

**Comment by ed-george** [comment]
Thanks a lot - will continue to help improve where I can 👍

**Pull request merged**
